export const BarData = {
  "maxNumber": 636224,
  "minNumber": 0,
  "numbers": [
    {
      "budget": 0,
      "currencyCode": null,
      "displayNumber": null,
      "displayNumberCurrencyCode": null,
      "displayNumberFormat": null,
      "for": null,
      "forecast": null,
      "format": "average/int",
      "health": null,
      "icon": null,
      "indicator": null,
      "label": "Baseline",
      "maxScale": null,
      "minScale": null,
      "number": 257000,
      "percentOfTotal": null,
      "target": 0,
      "trend": null,
      "units": null
    },
    {
      "budget": 257000,
      "currencyCode": null,
      "displayNumber": null,
      "displayNumberCurrencyCode": null,
      "displayNumberFormat": null,
      "for": null,
      "forecast": null,
      "format": "average/int",
      "health": null,
      "icon": null,
      "indicator": null,
      "label": "2016",
      "maxScale": null,
      "minScale": null,
      "number": 46088,
      "percentOfTotal": null,
      "target": 0,
      "trend": null,
      "units": null
    },
    {
      "budget": 303088,
      "currencyCode": null,
      "displayNumber": null,
      "displayNumberCurrencyCode": null,
      "displayNumberFormat": null,
      "for": null,
      "forecast": null,
      "format": "average/int",
      "health": null,
      "icon": null,
      "indicator": null,
      "label": "2017",
      "maxScale": null,
      "minScale": null,
      "number": 273854,
      "percentOfTotal": null,
      "target": 473792,
      "trend": null,
      "units": null
    },
    {
      "budget": 576942,
      "currencyCode": null,
      "displayNumber": null,
      "displayNumberCurrencyCode": null,
      "displayNumberFormat": null,
      "for": null,
      "forecast": null,
      "format": "average/int",
      "health": null,
      "icon": null,
      "indicator": null,
      "label": "2018",
      "maxScale": null,
      "minScale": null,
      "number": 59282,
      "percentOfTotal": null,
      "target": 776424,
      "trend": null,
      "units": null
    },
    {
      "budget": 636224,
      "currencyCode": null,
      "displayNumber": null,
      "displayNumberCurrencyCode": null,
      "displayNumberFormat": null,
      "for": null,
      "forecast": null,
      "format": "average/int",
      "health": null,
      "icon": null,
      "indicator": null,
      "label": "2019",
      "maxScale": null,
      "minScale": null,
      "number": 0,
      "percentOfTotal": null,
      "target": 766038,
      "trend": null,
      "units": null
    },
    {
      "budget": 0,
      "currencyCode": null,
      "displayNumber": null,
      "displayNumberCurrencyCode": null,
      "displayNumberFormat": null,
      "for": null,
      "forecast": null,
      "format": "average/int",
      "health": null,
      "icon": null,
      "indicator": null,
      "label": "Strive for Five Cumulative",
      "maxScale": null,
      "minScale": null,
      "number": 636224,
      "percentOfTotal": null,
      "target": 757000,
      "trend": null,
      "units": null
    }
  ]
};

export const TableData = {
  headers: [
    { title: 'sno', fieldName: 'id' }, { title: 'name', fieldName: 'fullname' }, { title: 'address', fieldName: 'address' }
  ],
  data: [
    { id: '1', fullname: 'kumar', address: 'monsanto' },
    { id: '2', fullname: 'kumar', address: 'monsanto' },
    { id: '3', fullname: 'kumar', address: 'monsanto' },
    { id: '4', fullname: 'kumar', address: 'monsanto' },
  ]
}